// Comprehensive error code system with both numeric codes and named constants
export const ERROR_CODES = {
	// General errors
	"GENERAL.001": "GENERAL.BAD_REQUEST",
	"GENERAL.002": "GENERAL.VALIDATION_ERROR",
	"GENERAL.003": "GENERAL.FORBIDDEN_ERROR",
	"GENERAL.004": "GENERAL.INTERNAL_SERVER_ERROR",
	"GENERAL.005": "GENERAL.UNAUTHORIZED",
	"GENERAL.006": "GENERAL.UNAUTHENTICATED",

	// Google/OAuth errors
	"GOOGLE.001": "GOOGLE.INVALID_ORIGIN_URI",
	"GOOGLE.002": "GOOGLE.INVALID_REDIRECT_URI",
	"GOOGLE.003": "GOOGLE.FAILED_TO_CALL_API",
	"GOOGLE.004": "GOOGLE.FAILED_LOGIN",
	"GOOGLE.005": "GOOGLE.FAILED_LOGOUT",
	"GOOGLE.006": "GOOGLE.FAILED_REFRESH_TOKEN",
	"GOOGLE.007": "GOOGLE.INVALID_PROVIDER_PASSED",

	// User errors
	"USER.001": "USER.NOT_FOUND",
	"USER.002": "USER.FAILED_TO_CREATE",
	"USER.003": "USER.FAILED_TO_UPDATE",
	"USER.004": "USER.FAILED_TO_DELETE",
	"USER.005": "USER.EMAIL_EXISTS",
	"USER.006": "USER.FAILED_TO_GET_UPLOAD_URL",

	// Role errors
	"ROLE.001": "ROLE.NOT_FOUND",
	"ROLE.002": "ROLE.FAILED_TO_CREATE",
	"ROLE.003": "ROLE.FAILED_TO_UPDATE",
	"ROLE.004": "ROLE.FAILED_TO_DELETE",
	"ROLE.005": "ROLE.FAILED_TO_GET_UPLOAD_URL",
	"ROLE.006": "ROLE.NAME_REQUIRED",
	"ROLE.007": "ROLE.TENANT_REQUIRED",

	// Category errors
	"CATEGORY.001": "CATEGORY.NOT_FOUND",
	"CATEGORY.002": "CATEGORY.FAILED_TO_CREATE",
	"CATEGORY.003": "CATEGORY.FAILED_TO_UPDATE",
	"CATEGORY.004": "CATEGORY.FAILED_TO_DELETE",
	"CATEGORY.005": "CATEGORY.FAILED_TO_GET_UPLOAD_URL",
	"CATEGORY.006": "CATEGORY.NAME_REQUIRED",
	"CATEGORY.007": "CATEGORY.BUSINESS_ID_REQUIRED",
	"CATEGORY.008": "CATEGORY.PARENT_ID_REQUIRED",

	// Policy errors
	"POLICY.001": "POLICY.POLICIES_REQUIRED",
	"POLICY.002": "POLICY.ACTION_REQUIRED",
	"POLICY.003": "POLICY.RULES_REQUIRED",

	// Tenant errors
	"TENANT.001": "TENANT.NOT_FOUND",
	"TENANT.002": "TENANT.FAILED_TO_CREATE",
	"TENANT.003": "TENANT.FAILED_TO_UPDATE",
	"TENANT.004": "TENANT.FAILED_TO_DELETE",
	"TENANT.005": "TENANT.FAILED_TO_GET_UPLOAD_URL",
	"TENANT.006": "TENANT.NAME_REQUIRED",

	// Provider Item errors
	"PROVIDER_ITEM.001": "PROVIDER_ITEM.NOT_FOUND",
	"PROVIDER_ITEM.002": "PROVIDER_ITEM.FAILED_TO_CREATE",
	"PROVIDER_ITEM.003": "PROVIDER_ITEM.FAILED_TO_UPDATE",
	"PROVIDER_ITEM.004": "PROVIDER_ITEM.FAILED_TO_DELETE",
	"PROVIDER_ITEM.005": "PROVIDER_ITEM.FAILED_TO_GET_UPLOAD_URL",

	// Provider errors  
	"PROVIDER.001": "PROVIDER.NOT_FOUND",
	"PROVIDER.002": "PROVIDER.FAILED_TO_CREATE",
	"PROVIDER.003": "PROVIDER.FAILED_TO_UPDATE",
	"PROVIDER.004": "PROVIDER.FAILED_TO_DELETE",
	"PROVIDER.005": "PROVIDER.FAILED_TO_GET_UPLOAD_URL",
	"PROVIDER.006": "PROVIDER.NAME_REQUIRED",
	"PROVIDER.007": "PROVIDER.BUSINESS_ID_REQUIRED",
	"PROVIDER.008": "PROVIDER.DESCRIPTION_REQUIRED",

	// Business errors
	"BUSINESS.001": "BUSINESS.NOT_FOUND",
	"BUSINESS.002": "BUSINESS.FAILED_TO_CREATE",
	"BUSINESS.003": "BUSINESS.FAILED_TO_UPDATE",
	"BUSINESS.004": "BUSINESS.FAILED_TO_DELETE",
	"BUSINESS.005": "BUSINESS.FAILED_TO_GET_UPLOAD_URL",
	"BUSINESS.006": "BUSINESS.NAME_REQUIRED",
	"BUSINESS.007": "BUSINESS.BUSINESS_ID_REQUIRED",
	"BUSINESS.010": "BUSINESS.DESCRIPTION_REQUIRED",
	"BUSINESS.011": "BUSINESS.SLUG_INVALID",

	// Business Service errors
	"BUSINESS_SERVICE.005": "BUSINESS_SERVICE.SLUG_INVALID",
};

// Named error constants for direct access
export const ERROR_CONSTANTS = {
	GENERAL: {
		BAD_REQUEST: "GENERAL.BAD_REQUEST",
		VALIDATION_ERROR: "GENERAL.VALIDATION_ERROR",
		FORBIDDEN_ERROR: "GENERAL.FORBIDDEN_ERROR",
		INTERNAL_SERVER_ERROR: "GENERAL.INTERNAL_SERVER_ERROR",
		UNAUTHORIZED: "GENERAL.UNAUTHORIZED",
		UNAUTHENTICATED: "GENERAL.UNAUTHENTICATED",
	},
	GOOGLE: {
		INVALID_ORIGIN_URI: "GOOGLE.INVALID_ORIGIN_URI",
		INVALID_REDIRECT_URI: "GOOGLE.INVALID_REDIRECT_URI",
		FAILED_TO_CALL_API: "GOOGLE.FAILED_TO_CALL_API",
		FAILED_LOGIN: "GOOGLE.FAILED_LOGIN",
		FAILED_LOGOUT: "GOOGLE.FAILED_LOGOUT",
		FAILED_REFRESH_TOKEN: "GOOGLE.FAILED_REFRESH_TOKEN",
		INVALID_PROVIDER_PASSED: "GOOGLE.INVALID_PROVIDER_PASSED",
	},
	USER: {
		NOT_FOUND: "USER.NOT_FOUND",
		FAILED_TO_CREATE: "USER.FAILED_TO_CREATE",
		FAILED_TO_UPDATE: "USER.FAILED_TO_UPDATE",
		FAILED_TO_DELETE: "USER.FAILED_TO_DELETE",
		EMAIL_EXISTS: "USER.EMAIL_EXISTS",
		FAILED_TO_GET_UPLOAD_URL: "USER.FAILED_TO_GET_UPLOAD_URL",
	},
	PROVIDER: {
		NOT_FOUND: "PROVIDER.NOT_FOUND",
		FAILED_TO_CREATE: "PROVIDER.FAILED_TO_CREATE",
		FAILED_TO_UPDATE: "PROVIDER.FAILED_TO_UPDATE",
		FAILED_TO_DELETE: "PROVIDER.FAILED_TO_DELETE",
		FAILED_TO_GET_UPLOAD_URL: "PROVIDER.FAILED_TO_GET_UPLOAD_URL",
		NAME_REQUIRED: "PROVIDER.NAME_REQUIRED",
		BUSINESS_ID_REQUIRED: "PROVIDER.BUSINESS_ID_REQUIRED",
		DESCRIPTION_REQUIRED: "PROVIDER.DESCRIPTION_REQUIRED",
	},
	BUSINESS: {
		NOT_FOUND: "BUSINESS.NOT_FOUND",
		FAILED_TO_CREATE: "BUSINESS.FAILED_TO_CREATE",
		FAILED_TO_UPDATE: "BUSINESS.FAILED_TO_UPDATE",
		FAILED_TO_DELETE: "BUSINESS.FAILED_TO_DELETE",
		FAILED_TO_GET_UPLOAD_URL: "BUSINESS.FAILED_TO_GET_UPLOAD_URL",
		NAME_REQUIRED: "BUSINESS.NAME_REQUIRED",
		BUSINESS_ID_REQUIRED: "BUSINESS.BUSINESS_ID_REQUIRED",
		DESCRIPTION_REQUIRED: "BUSINESS.DESCRIPTION_REQUIRED",
		SLUG_INVALID: "BUSINESS.SLUG_INVALID",
	},
};

// Utility functions for error handling
export function getErrorMessage(code: string): string {
	return ERROR_CODES[code] || code;
}

export function isErrorCode(code: string): boolean {
	return code in ERROR_CODES;
}

// Default export for backward compatibility
export default ERROR_CODES;