export const countries = [
	{ iso: 'US', code: '+1', name: 'United States', flag: '🇺🇸' },
	{ iso: 'CA', code: '+1', name: 'Canada', flag: '🇨🇦' },
	{ iso: 'GB', code: '+44', name: 'United Kingdom', flag: '🇬🇧' },
	{ iso: 'FR', code: '+33', name: 'France', flag: '🇫🇷' },
	{ iso: 'DE', code: '+49', name: 'Germany', flag: '🇩🇪' },
	{ iso: 'IT', code: '+39', name: 'Italy', flag: '🇮🇹' },
	{ iso: 'ES', code: '+34', name: 'Spain', flag: '🇪🇸' },
	{ iso: 'NL', code: '+31', name: 'Netherlands', flag: '🇳🇱' },
	{ iso: 'BE', code: '+32', name: 'Belgium', flag: '🇧🇪' },
	{ iso: 'AT', code: '+43', name: 'Austria', flag: '🇦🇹' },
	{ iso: 'CH', code: '+41', name: 'Switzerland', flag: '🇨🇭' },
	{ iso: 'SE', code: '+46', name: 'Sweden', flag: '🇸🇪' },
	{ iso: 'NO', code: '+47', name: 'Norway', flag: '🇳🇴' },
	{ iso: 'DK', code: '+45', name: 'Denmark', flag: '🇩🇰' },
	{ iso: 'FI', code: '+358', name: 'Finland', flag: '🇫🇮' },
	{ iso: 'PL', code: '+48', name: 'Poland', flag: '🇵🇱' },
	{ iso: 'CZ', code: '+420', name: 'Czech Republic', flag: '🇨🇿' },
	{ iso: 'SK', code: '+421', name: 'Slovakia', flag: '🇸🇰' },
	{ iso: 'HU', code: '+36', name: 'Hungary', flag: '🇭🇺' },
	{ iso: 'SI', code: '+386', name: 'Slovenia', flag: '🇸🇮' },
	{ iso: 'HR', code: '+385', name: 'Croatia', flag: '🇭🇷' },
	{ iso: 'BA', code: '+387', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
	{ iso: 'RS', code: '+381', name: 'Serbia', flag: '🇷🇸' },
	{ iso: 'ME', code: '+382', name: 'Montenegro', flag: '🇲🇪' },
	{ iso: 'MK', code: '+389', name: 'North Macedonia', flag: '🇲🇰' },
	{ iso: 'AL', code: '+355', name: 'Albania', flag: '🇦🇱' },
	{ iso: 'BG', code: '+359', name: 'Bulgaria', flag: '🇧🇬' },
	{ iso: 'RO', code: '+40', name: 'Romania', flag: '🇷🇴' },
	{ iso: 'GR', code: '+30', name: 'Greece', flag: '🇬🇷' },
	{ iso: 'TR', code: '+90', name: 'Turkey', flag: '🇹🇷' },
	{ iso: 'RU', code: '+7', name: 'Russia', flag: '🇷🇺' },
	{ iso: 'UA', code: '+380', name: 'Ukraine', flag: '🇺🇦' },
	{ iso: 'BY', code: '+375', name: 'Belarus', flag: '🇧🇾' },
	{ iso: 'LT', code: '+370', name: 'Lithuania', flag: '🇱🇹' },
	{ iso: 'LV', code: '+371', name: 'Latvia', flag: '🇱🇻' },
	{ iso: 'EE', code: '+372', name: 'Estonia', flag: '🇪🇪' },
	{ iso: 'JP', code: '+81', name: 'Japan', flag: '🇯🇵' },
	{ iso: 'KR', code: '+82', name: 'South Korea', flag: '🇰🇷' },
	{ iso: 'CN', code: '+86', name: 'China', flag: '🇨🇳' },
	{ iso: 'IN', code: '+91', name: 'India', flag: '🇮🇳' },
	{ iso: 'AU', code: '+61', name: 'Australia', flag: '🇦🇺' },
	{ iso: 'NZ', code: '+64', name: 'New Zealand', flag: '🇳🇿' },
	{ iso: 'BR', code: '+55', name: 'Brazil', flag: '🇧🇷' },
	{ iso: 'MX', code: '+52', name: 'Mexico', flag: '🇲🇽' },
	{ iso: 'AR', code: '+54', name: 'Argentina', flag: '🇦🇷' },
	{ iso: 'CL', code: '+56', name: 'Chile', flag: '🇨🇱' },
	{ iso: 'CO', code: '+57', name: 'Colombia', flag: '🇨🇴' },
	{ iso: 'PE', code: '+51', name: 'Peru', flag: '🇵🇪' },
	{ iso: 'VE', code: '+58', name: 'Venezuela', flag: '🇻🇪' },
	{ iso: 'ZA', code: '+27', name: 'South Africa', flag: '🇿🇦' },
	{ iso: 'EG', code: '+20', name: 'Egypt', flag: '🇪🇬' },
	{ iso: 'NG', code: '+234', name: 'Nigeria', flag: '🇳🇬' },
	{ iso: 'KE', code: '+254', name: 'Kenya', flag: '🇰🇪' },
	{ iso: 'GH', code: '+233', name: 'Ghana', flag: '🇬🇭' },
	{ iso: 'TN', code: '+216', name: 'Tunisia', flag: '🇹🇳' },
	{ iso: 'MA', code: '+212', name: 'Morocco', flag: '🇲🇦' },
	{ iso: 'DZ', code: '+213', name: 'Algeria', flag: '🇩🇿' },
	{ iso: 'IL', code: '+972', name: 'Israel', flag: '🇮🇱' },
	{ iso: 'AE', code: '+971', name: 'United Arab Emirates', flag: '🇦🇪' },
	{ iso: 'SA', code: '+966', name: 'Saudi Arabia', flag: '🇸🇦' },
	{ iso: 'QA', code: '+974', name: 'Qatar', flag: '🇶🇦' },
	{ iso: 'KW', code: '+965', name: 'Kuwait', flag: '🇰🇼' },
	{ iso: 'BH', code: '+973', name: 'Bahrain', flag: '🇧🇭' },
	{ iso: 'OM', code: '+968', name: 'Oman', flag: '🇴🇲' },
	{ iso: 'JO', code: '+962', name: 'Jordan', flag: '🇯🇴' },
	{ iso: 'LB', code: '+961', name: 'Lebanon', flag: '🇱🇧' },
	{ iso: 'SY', code: '+963', name: 'Syria', flag: '🇸🇾' },
	{ iso: 'IQ', code: '+964', name: 'Iraq', flag: '🇮🇶' },
	{ iso: 'IR', code: '+98', name: 'Iran', flag: '🇮🇷' },
	{ iso: 'AF', code: '+93', name: 'Afghanistan', flag: '🇦🇫' },
	{ iso: 'PK', code: '+92', name: 'Pakistan', flag: '🇵🇰' },
	{ iso: 'BD', code: '+880', name: 'Bangladesh', flag: '🇧🇩' },
	{ iso: 'LK', code: '+94', name: 'Sri Lanka', flag: '🇱🇰' },
	{ iso: 'MY', code: '+60', name: 'Malaysia', flag: '🇲🇾' },
	{ iso: 'SG', code: '+65', name: 'Singapore', flag: '🇸🇬' },
	{ iso: 'TH', code: '+66', name: 'Thailand', flag: '🇹🇭' },
	{ iso: 'VN', code: '+84', name: 'Vietnam', flag: '🇻🇳' },
	{ iso: 'PH', code: '+63', name: 'Philippines', flag: '🇵🇭' },
	{ iso: 'ID', code: '+62', name: 'Indonesia', flag: '🇮🇩' },
	{ iso: 'MM', code: '+95', name: 'Myanmar', flag: '🇲🇲' },
	{ iso: 'KH', code: '+855', name: 'Cambodia', flag: '🇰🇭' },
	{ iso: 'LA', code: '+856', name: 'Laos', flag: '🇱🇦' },
	{ iso: 'BN', code: '+673', name: 'Brunei', flag: '🇧🇳' },
	{ iso: 'MN', code: '+976', name: 'Mongolia', flag: '🇲🇳' },
	{ iso: 'TJ', code: '+992', name: 'Tajikistan', flag: '🇹🇯' },
	{ iso: 'KG', code: '+996', name: 'Kyrgyzstan', flag: '🇰🇬' },
	{ iso: 'KZ', code: '+7', name: 'Kazakhstan', flag: '🇰🇿' },
	{ iso: 'UZ', code: '+998', name: 'Uzbekistan', flag: '🇺🇿' },
	{ iso: 'TM', code: '+993', name: 'Turkmenistan', flag: '🇹🇲' },
	{ iso: 'AZ', code: '+994', name: 'Azerbaijan', flag: '🇦🇿' },
	{ iso: 'AM', code: '+374', name: 'Armenia', flag: '🇦🇲' },
	{ iso: 'GE', code: '+995', name: 'Georgia', flag: '🇬🇪' },
];