export const countries = [
	{ code: '+93', name: 'Afghanistan', flag: '🇦🇫', iso: 'AF' },
	{ code: '+355', name: 'Albania', flag: '🇦🇱', iso: 'AL' },
	{ code: '+213', name: 'Algeria', flag: '🇩🇿', iso: 'DZ' },
	{ code: '+1', name: 'United States', flag: '🇺🇸', iso: 'US' },
	{ code: '+376', name: 'Andorra', flag: '🇦🇩', iso: 'AD' },
	{ code: '+244', name: 'Angola', flag: '🇦🇴', iso: 'AO' },
	{ code: '+54', name: 'Argentina', flag: '🇦🇷', iso: 'AR' },
	{ code: '+374', name: 'Armenia', flag: '🇦🇲', iso: 'AM' },
	{ code: '+61', name: 'Australia', flag: '🇦🇺', iso: 'AU' },
	{ code: '+43', name: 'Austria', flag: '🇦🇹', iso: 'AT' },
	{ code: '+994', name: 'Azerbaijan', flag: '🇦🇿', iso: 'AZ' },
	{ code: '+973', name: 'Bahrain', flag: '🇧🇭', iso: 'BH' },
	{ code: '+880', name: 'Bangladesh', flag: '🇧🇩', iso: 'BD' },
	{ code: '+375', name: 'Belarus', flag: '🇧🇾', iso: 'BY' },
	{ code: '+32', name: 'Belgium', flag: '🇧🇪', iso: 'BE' },
	{ code: '+501', name: 'Belize', flag: '🇧🇿', iso: 'BZ' },
	{ code: '+229', name: 'Benin', flag: '🇧🇯', iso: 'BJ' },
	{ code: '+387', name: 'Bosnia and Herzegovina', flag: '🇧🇦', iso: 'BA' },
	{ code: '+267', name: 'Botswana', flag: '🇧🇼', iso: 'BW' },
	{ code: '+55', name: 'Brazil', flag: '🇧🇷', iso: 'BR' },
	{ code: '+359', name: 'Bulgaria', flag: '🇧🇬', iso: 'BG' },
	{ code: '+1', name: 'Canada', flag: '🇨🇦', iso: 'CA' },
	{ code: '+56', name: 'Chile', flag: '🇨🇱', iso: 'CL' },
	{ code: '+86', name: 'China', flag: '🇨🇳', iso: 'CN' },
	{ code: '+57', name: 'Colombia', flag: '🇨🇴', iso: 'CO' },
	{ code: '+385', name: 'Croatia', flag: '🇭🇷', iso: 'HR' },
	{ code: '+420', name: 'Czech Republic', flag: '🇨🇿', iso: 'CZ' },
	{ code: '+45', name: 'Denmark', flag: '🇩🇰', iso: 'DK' },
	{ code: '+20', name: 'Egypt', flag: '🇪🇬', iso: 'EG' },
	{ code: '+372', name: 'Estonia', flag: '🇪🇪', iso: 'EE' },
	{ code: '+358', name: 'Finland', flag: '🇫🇮', iso: 'FI' },
	{ code: '+33', name: 'France', flag: '🇫🇷', iso: 'FR' },
	{ code: '+995', name: 'Georgia', flag: '🇬🇪', iso: 'GE' },
	{ code: '+49', name: 'Germany', flag: '🇩🇪', iso: 'DE' },
	{ code: '+233', name: 'Ghana', flag: '🇬🇭', iso: 'GH' },
	{ code: '+30', name: 'Greece', flag: '🇬🇷', iso: 'GR' },
	{ code: '+36', name: 'Hungary', flag: '🇭🇺', iso: 'HU' },
	{ code: '+354', name: 'Iceland', flag: '🇮🇸', iso: 'IS' },
	{ code: '+91', name: 'India', flag: '🇮🇳', iso: 'IN' },
	{ code: '+62', name: 'Indonesia', flag: '🇮🇩', iso: 'ID' },
	{ code: '+98', name: 'Iran', flag: '🇮🇷', iso: 'IR' },
	{ code: '+964', name: 'Iraq', flag: '🇮🇶', iso: 'IQ' },
	{ code: '+353', name: 'Ireland', flag: '🇮🇪', iso: 'IE' },
	{ code: '+972', name: 'Israel', flag: '🇮🇱', iso: 'IL' },
	{ code: '+39', name: 'Italy', flag: '🇮🇹', iso: 'IT' },
	{ code: '+81', name: 'Japan', flag: '🇯🇵', iso: 'JP' },
	{ code: '+962', name: 'Jordan', flag: '🇯🇴', iso: 'JO' },
	{ code: '+7', name: 'Kazakhstan', flag: '🇰🇿', iso: 'KZ' },
	{ code: '+254', name: 'Kenya', flag: '🇰🇪', iso: 'KE' },
	{ code: '+82', name: 'South Korea', flag: '🇰🇷', iso: 'KR' },
	{ code: '+965', name: 'Kuwait', flag: '🇰🇼', iso: 'KW' },
	{ code: '+371', name: 'Latvia', flag: '🇱🇻', iso: 'LV' },
	{ code: '+961', name: 'Lebanon', flag: '🇱🇧', iso: 'LB' },
	{ code: '+370', name: 'Lithuania', flag: '🇱🇹', iso: 'LT' },
	{ code: '+352', name: 'Luxembourg', flag: '🇱🇺', iso: 'LU' },
	{ code: '+60', name: 'Malaysia', flag: '🇲🇾', iso: 'MY' },
	{ code: '+52', name: 'Mexico', flag: '🇲🇽', iso: 'MX' },
	{ code: '+373', name: 'Moldova', flag: '🇲🇩', iso: 'MD' },
	{ code: '+382', name: 'Montenegro', flag: '🇲🇪', iso: 'ME' },
	{ code: '+212', name: 'Morocco', flag: '🇲🇦', iso: 'MA' },
	{ code: '+31', name: 'Netherlands', flag: '🇳🇱', iso: 'NL' },
	{ code: '+64', name: 'New Zealand', flag: '🇳🇿', iso: 'NZ' },
	{ code: '+234', name: 'Nigeria', flag: '🇳🇬', iso: 'NG' },
	{ code: '+383', name: 'Kosovo', flag: '🇽🇰', iso: 'XK' },
	{ code: '+389', name: 'North Macedonia', flag: '🇲🇰', iso: 'MK' },
	{ code: '+47', name: 'Norway', flag: '🇳🇴', iso: 'NO' },
	{ code: '+92', name: 'Pakistan', flag: '🇵🇰', iso: 'PK' },
	{ code: '+507', name: 'Panama', flag: '🇵🇦', iso: 'PA' },
	{ code: '+51', name: 'Peru', flag: '🇵🇪', iso: 'PE' },
	{ code: '+63', name: 'Philippines', flag: '🇵🇭', iso: 'PH' },
	{ code: '+48', name: 'Poland', flag: '🇵🇱', iso: 'PL' },
	{ code: '+351', name: 'Portugal', flag: '🇵🇹', iso: 'PT' },
	{ code: '+974', name: 'Qatar', flag: '🇶🇦', iso: 'QA' },
	{ code: '+40', name: 'Romania', flag: '🇷🇴', iso: 'RO' },
	{ code: '+7', name: 'Russia', flag: '🇷🇺', iso: 'RU' },
	{ code: '+966', name: 'Saudi Arabia', flag: '🇸🇦', iso: 'SA' },
	{ code: '+381', name: 'Serbia', flag: '🇷🇸', iso: 'RS' },
	{ code: '+65', name: 'Singapore', flag: '🇸🇬', iso: 'SG' },
	{ code: '+421', name: 'Slovakia', flag: '🇸🇰', iso: 'SK' },
	{ code: '+386', name: 'Slovenia', flag: '🇸🇮', iso: 'SI' },
	{ code: '+27', name: 'South Africa', flag: '🇿🇦', iso: 'ZA' },
	{ code: '+34', name: 'Spain', flag: '🇪🇸', iso: 'ES' },
	{ code: '+94', name: 'Sri Lanka', flag: '🇱🇰', iso: 'LK' },
	{ code: '+46', name: 'Sweden', flag: '🇸🇪', iso: 'SE' },
	{ code: '+41', name: 'Switzerland', flag: '🇨🇭', iso: 'CH' },
	{ code: '+963', name: 'Syria', flag: '🇸🇾', iso: 'SY' },
	{ code: '+886', name: 'Taiwan', flag: '🇹🇼', iso: 'TW' },
	{ code: '+66', name: 'Thailand', flag: '🇹🇭', iso: 'TH' },
	{ code: '+90', name: 'Turkey', flag: '🇹🇷', iso: 'TR' },
	{ code: '+380', name: 'Ukraine', flag: '🇺🇦', iso: 'UA' },
	{ code: '+971', name: 'United Arab Emirates', flag: '🇦🇪', iso: 'AE' },
	{ code: '+44', name: 'United Kingdom', flag: '🇬🇧', iso: 'GB' },
	{ code: '+598', name: 'Uruguay', flag: '🇺🇾', iso: 'UY' },
	{ code: '+58', name: 'Venezuela', flag: '🇻🇪', iso: 'VE' },
	{ code: '+84', name: 'Vietnam', flag: '🇻🇳', iso: 'VN' }
];

// Popular countries for quick access
export const popularCountries = [
	{ code: '+387', name: 'Bosnia and Herzegovina', flag: '🇧🇦', iso: 'BA' },
	{ code: '+381', name: 'Serbia', flag: '🇷🇸', iso: 'RS' },
	{ code: '+385', name: 'Croatia', flag: '🇭🇷', iso: 'HR' },
	{ code: '+382', name: 'Montenegro', flag: '🇲🇪', iso: 'ME' },
	{ code: '+383', name: 'Kosovo', flag: '🇽🇰', iso: 'XK' },
	{ code: '+386', name: 'Slovenia', flag: '🇸🇮', iso: 'SI' },
	{ code: '+389', name: 'North Macedonia', flag: '🇲🇰', iso: 'MK' },
	{ code: '+1', name: 'United States', flag: '🇺🇸', iso: 'US' },
	{ code: '+49', name: 'Germany', flag: '🇩🇪', iso: 'DE' },
	{ code: '+33', name: 'France', flag: '🇫🇷', iso: 'FR' },
	{ code: '+44', name: 'United Kingdom', flag: '🇬🇧', iso: 'GB' }
];