name: Deploy Infrastructure

on:
  push:
    branches: ["master"]
env:
  TF_VAR_ROOT_DOMAIN: ${{ secrets.ROOT_DOMAIN }}
  TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  TF_VAR_CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  TF_VAR_GITHUB_OWNER: ${{ github.repository_owner }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: |
          git pull origin master

      - name: Terraform Init
        working-directory: ./deploy
        run: terraform init

      - name: Terraform Plan
        working-directory: ./deploy
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./deploy
        run: terraform apply -auto-approve tfplan

      - name: Commit state file
        run: |
          git add deploy/terraform.tfstate 
          git diff --staged --quiet || git commit -m "Update Terraform state"
          git push origin master
